version: '3.8'

services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: lunch_voting_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2xy1605b
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: ./entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:2xy1605b@db/lunch_voting_db

volumes:
  postgres_data: