# Generated by Django 5.1.1 on 2024-09-27 21:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='employee',
            name='department',
            field=models.TextField(choices=[('developer', 'Developer'), ('tester', 'Tester'), ('designer', 'Designer')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
