# Generated by Django 5.1.1 on 2024-09-27 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_employee_restaurant_employee_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.TextField(choices=[('developer', 'Developer'), ('tester', 'Tester'), ('designer', 'Designer'), ('devops', 'DevOps'), ('business analysis', 'Business Analysis')], max_length=20),
        ),
    ]
